### ISSUE TITLE
[feature request] 自定义buffer size

### ISSUE THREAD

**Issue by arily** [XTXTMTXTX/osu-External-ASIO-Sound#1]
现在的5ms对于asio音效确实有点高了

**Comment by XTXTMTXTX** [comment]
创个快捷方式 目标后面加空格和buffer size
比如 osu!asio_sound.exe 64
其实程序间通讯也有1~3ms的延迟（大概
还有 asio4all 貌似最低只支持到 64，再低就没声儿了

**Comment by arily** [comment]
如果用真的支持asio声卡的话还是可以压到更低的
ur22mk2可以在192Khz@16smp的情况到0.16ms

(其实asio4all能带来的提升感觉很有限)

**Comment by XTXTMTXTX** [comment]
相比没有导致的40ms延迟还算比较可观了
顺便貌似一些垃圾声卡声称asio其实用的也不是asio，专业声卡预算可能有点起飞（
