### ISSUE TITLE
有没有办法支持其他修改客户端

### ISSUE THREAD

**Issue by arily** [XTXTMTXTX/osu-External-ASIO-Sound#2]
有些私服会定制客户端,他好像没有办法hook上

**Comment by XTXTMTXTX** [comment]
试着先打开私服进入游戏过几秒再开这个软件看看呢？
难道说是重新弄了个别的 .exe（

**Comment by arily** [comment]
对的 是别的.exe

**Comment by arily** [comment]
我觉得比较简单的办法是把私服的exe(或者bancho)拖到你的应用程序 然后你的应用程序启动osu (会不会有点麻烦

**Comment by XTXTMTXTX** [comment]
改完了 输入带后缀的文件名 你试试 [1.2.2](https://github.com/XTXTMTXTX/osu-External-ASIO-Sound/releases/tag/1.2.2)

**Comment by arily** [comment]
确认可用!!谢谢
