### ISSUE TITLE
[readme] 在显要位置声明风险

### ISSUE THREAD

**Issue by arily** [XTXTMTXTX/osu-External-ASIO-Sound#3]
https://github.com/ppy/osu-stable-issues/issues/549
似乎ppy不太喜欢.
不过我不太懂他说的情况, 总之通知一下owner111

**Comment by XTXTMTXTX** [comment]
马上加
应该是客户端校验的问题，建议正常启动顺序是登录osu之后再运行这个软件
当然最保险的还是离线游玩，毕竟hook逃不开修改内存，虽然不是干什么坏事

**Comment by arily** [comment]
很可惜ppy对待这种事情持很不开放的态度
（他可能已经很烦别人动他的游戏了）
