### ISSUE TITLE
feature request: force sample rate

### ISSUE THREAD

**Issue by arily** [XTXTMTXTX/osu-External-ASIO-Sound#4]
every time I restart the program it fallbacks to 48000hz which introduces a bunch of latency

**Comment by arily** [comment]
5ms~ since my interface cannot do below 128smps

**Comment by XTXTMTXTX** [comment]
Added
[1.3.0](https://github.com/XTXTMTXTX/osu-External-ASIO-Sound/releases/tag/1.3.0)

**Comment by arily** [comment]
Fast

**Comment by arily** [comment]
I would suggest to use current sample rate when leaving the sample rate blank?

**Comment by XTXTMTXTX** [comment]
[1.3.1](https://github.com/XTXTMTXTX/osu-External-ASIO-Sound/releases/tag/1.3.1)
